### ISSUE TITLE
Support of SVG elements

### ISSUE THREAD

**Issue by hasalex** [medikoo/bespoke-substeps#3]
The dataset element is not supported yet on SVGElement (see https://developer.mozilla.org/en-US/docs/Web/API/SVGElement/dataset#Browser_compatibility).

By adding a simple test on el.dataset, you would add a basic support of subsets in SVG:

`var order = el.dataset && Number(el.dataset.order)`

**Comment by medikoo** [comment]
@hasalex yes, true still without `dataset` support it can only work in default mode, so very limited.

I'd say that recommendation would be to wrap svg elements with span or div elements, and instead of supporting SVG (in such case) probably util should abort with more meaningful information

**Comment by medikoo** [comment]
I published fix with v1.0.0

Instead of crashing it now reports in a console unability to use substeps with elements that do not support `dataset` and lets presentation be rendered without that function. As a real fix I suggest to use span or div wrapper over SVG

**Comment by hasalex** [comment]
That's much better. It's easier to understand.

But having steps in a svg image is a great feature, and your fix don't enable it. A simple `if` would bring the feature at the same level as the bespoke-step plug-in.

**Comment by medikoo** [comment]
@hasalex what you propose would bring partial support, and that would be very confusing.
Imagine setup as:
```html
<svg class="substep" data-order="5">..</svg>
```
As you can imagine substep will work, but will occur not in expected order, I will probably receive another bug report for that :)

I think either functionality should be supported in full scope or not at all.

Also in this case workaround is very easy, why don't you just wrap `<svg>` with `<span>` and place class on span?

**Comment by hasalex** [comment]
I can understand your concern. What about changing your `console.error` into a `console.warn` ?

And your workaround make just possible to put the whole image in a step, and not the elements of the image.

**Comment by hasalex** [comment]
On the other hand, it works with Chrome Canary (57). That's enough for me, I can use it to have my steps in SVG.

**Comment by medikoo** [comment]
> I can understand your concern. What about changing your console.error into a console.warn ?

I think it should be more error, as behavior may be unexpected, e.g. if it's third step that's rejected, the third step will be visible immediately while two first will be on hold

> And your workaround make just possible to put the whole image in a step, and not the elements of the image.

Ok so you wanted to substep part of SVG structure (?) indeed in such case there's no workaround.

The only solution would be support cases where no `dataset` is implemented. Not that difficult to achieve, I'm open for Pull Request that brings that
